name: Build/release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Build for windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win64
