name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      
      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        
      - name: Build for macos
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
            
      - name: Build for windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win64
          
      - name: Set VERSION variable for macos/ubuntu
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: |
          echo "VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)" >> $GITHUB_ENV
          
      - name: Set VERSION variable for windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "VERSION=$(node -pe "require('./package.json').version")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
  
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: MediaDB-${{ env.VERSION }}-${{ runner.os }}-amd64
          path: dist
